version: '3.8'

services:
  app:
    build: .
    container_name: node_auth_app
    ports:
      - "3000:3000"       
    environment:
      - NODE_ENV=development
      - PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
